### PR TITLE
Try to add an OSX build

### PR DESCRIPTION
**Pull request by dstansby**

### CODE REVIEW

**Comment by Cadair** [comment]
surely we should not be pulling vtk from defaults: https://travis-ci.org/conda-forge/mayavi-feedstock/jobs/376586353#L317 ?

**Comment by dstansby** [comment]
There is no VTK package on conda-forge for macOS 😢  https://anaconda.org/conda-forge/vtk (https://github.com/conda-forge/vtk-feedstock/issues/47)

**Comment by Cadair** [comment]
So 4.6.0 has been released, so we should probably do an upgrade to that with PyQt5 and then hopefully mac should come along for the ride.

**Comment by christianbrodbeck** [comment]
Is there a way to get more info about that error? `subprocess.CalledProcessError: Command '['/bin/bash', '-e', '/Users/travis/miniconda3/conda-bld/mayavi_1527335656968/work/conda_build.sh']' returned non-zero exit status 1.`

**Comment by Cadair** [comment]
I think @mwcraig has taken a different stab at this, which he says worked on his machine. iirc it's related to the xvfb stuff in the build script.

**Comment by dstansby** [comment]
I've force rebased this on to all the recent changes, lets see what happens...

**Comment by christianbrodbeck** [comment]
@mwcraig do you have a working recipe that you would not mind sharing? Being able to upload to a different channel would already be better than not having it on `conda` at all.

**Comment by mwcraig** [comment]
@christianbrodbeck -- I never quite worked it up into a full recipe. It is failing on https://github.com/conda-forge/mayavi-feedstock/blob/master/recipe/build.sh#L7 so I commented that out  and the build succeeded. I still couldn't run mayavi because of vtk issues.

I think you could safely delete those lines in all cases (or maybe add a check for os if it is necessary on linux).

**Pull request closed without merging**
