### PR TITLE
CI: Test building

### PR DESCRIPTION
**Pull request by larsoner**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by larsoner** [comment]
FYI I'm testing to see if builds are okay with no changes @hoechenberger, then I'll try a rerender

**Comment by hoechenberger** [comment]
I don't understand why you're doing this :) only the ARM64 builds were genuinely failing, the Windows builds suffered from a problem with conda-build 

But let's talk in 30 mins!! 👋

**Comment by larsoner** [comment]
> the Windows builds suffered from a problem with conda-build

Yes I'm testing to see if this is the case with no changes to the `mayavi-feedstock` whatsoever. It will tell us if it's something about the infrastructure itself (if it fails now), or something about the latest rerender (if it fails after I ask for a rerender), or something about the ARM migration scripts (if both of the preceding steps succeed)

**Comment by larsoner** [comment]
I'm going to kill this one since https://github.com/conda/conda-build/pull/4482 will almost certainly fix Windows for us

**Pull request closed without merging**
