### PR TITLE
Enable osx build

### PR DESCRIPTION
**Pull request by christianbrodbeck**
Thanks @mwcraig https://github.com/conda-forge/mayavi-feedstock/pull/19#issuecomment-404722373, so disabling that command makes the builds pass on [here](https://travis-ci.org/christianbrodbeck/mayavi-feedstock/builds/403594682) as well. You were saying that there were `vtk` issues with the build though?

### CODE REVIEW

**Comment by mwcraig** [comment]
Yeah, different errors with the conda-forge vtk and the defaults vtk. I can get you details in about an hour. I can also see if the mayavi folks at scipy can help debug it

**Comment by christianbrodbeck** [comment]
Is there a way of test-installing the PR build?

**Comment by christianbrodbeck** [comment]
After installing a build made with `$ conda build` locally (with the `conda-forge` recipe) I got the error below. This lead me to [this](https://github.com/enthought/mayavi/issues/652) discussion, suggesting that this has to do with package management. Since this does not seem to happen anymore for windows/linux installations from conda-forge has this been fixed in a way that only works when installing from conda-forge directly?

```
>>> from mayavi import mlab
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda/envs/m36/lib/python3.6/site-packages/mayavi/mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "//anaconda/envs/m36/lib/python3.6/site-packages/mayavi/tools/camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "//anaconda/envs/m36/lib/python3.6/site-packages/mayavi/tools/engine_manager.py", line 14, in <module>
    from mayavi.core.engine import Engine
  File "//anaconda/envs/m36/lib/python3.6/site-packages/mayavi/core/engine.py", line 34, in <module>
    from mayavi.core.ui.mayavi_scene import viewer_factory
  File "//anaconda/envs/m36/lib/python3.6/site-packages/mayavi/core/ui/mayavi_scene.py", line 12, in <module>
    from tvtk.tools.ivtk import IVTK
  File "//anaconda/envs/m36/lib/python3.6/site-packages/tvtk/tools/ivtk.py", line 35, in <module>
    from tvtk.pyface.api import Scene, DecoratedScene
  File "//anaconda/envs/m36/lib/python3.6/site-packages/tvtk/pyface/api.py", line 1, in <module>
    from .decorated_scene import DecoratedScene
  File "//anaconda/envs/m36/lib/python3.6/site-packages/tvtk/pyface/decorated_scene.py", line 12, in <module>
    from tvtk.pyface.toolkit import toolkit_object
  File "//anaconda/envs/m36/lib/python3.6/site-packages/tvtk/pyface/toolkit.py", line 3, in <module>
    toolkit = toolkit_object = find_toolkit('tvtk.toolkits')
  File "//anaconda/envs/m36/lib/python3.6/site-packages/pyface/base_toolkit.py", line 263, in find_toolkit
    return import_toolkit(ETSConfig.toolkit, entry_point)
  File "//anaconda/envs/m36/lib/python3.6/site-packages/pyface/base_toolkit.py", line 217, in import_toolkit
    toolkit_object = plugin.load()
  File "//anaconda/envs/m36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2317, in load
    self.require(*args, **kwargs)
  File "//anaconda/envs/m36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2340, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "//anaconda/envs/m36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 774, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'vtk' distribution was not found and is required by the application
```

**Comment by mwcraig** [comment]
@christianbrodbeck -- that is the same error I was seeing too. Thanks for tracking down that link. I'll connect with Prabu (he is at scipy this year) and see if we can get this fixed during the scipy sprints tomorrow. I'm also a part of conda-forge so we should be able to get the problem presolved this weekend.

**Comment by christianbrodbeck** [comment]
Thanks @mwcraig, that would be great!

**Comment by mwcraig** [comment]
@christianbrodbeck -- fyi, https://github.com/conda-forge/vtk-feedstock/pull/64

**Comment by christianbrodbeck** [comment]
Is there a way to test that the new change works? Add `mayavi.mlab` to import tests?

**Comment by mwcraig** [comment]
I think that should do the trick. It is a `__requires__` in one of the `__init__.py` in mayavi that was causing the issue.

I just merged the vtk change a little while ago, so it may take some time for the new build to be available (but less than 24 hours).

**Comment by christianbrodbeck** [comment]
> I just merged the vtk change a little while ago, so it may take some time for the new build to be available

Hopefully that will allow the new test to fail and then succeed :)

**Comment by christianbrodbeck** [comment]
Now the [Python 3.6 build](https://travis-ci.org/conda-forge/mayavi-feedstock/jobs/405462440) gets this error on `mayavi.mlab` import:

```
  File "/Users/travis/miniconda3/conda-bld/mayavi_1531943534865/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.6/site-packages/apptools/scripting/recorder.py", line 15, in <module>
    import __builtin__
ModuleNotFoundError: No module named '__builtin__'
```

This import seems to be in [`apptools` master](https://github.com/enthought/apptools/blob/master/apptools/scripting/recorder.py). Is there some `future` type dependency missing from its build?

**Comment by mwcraig** [comment]
Looks like the fun never ends...in Python 3, `__builtin__` became `builtins` according to https://stackoverflow.com/a/11181607/3486425. So I'm guessing apptools needs a PR to make it python 3 compatible?

**Comment by christianbrodbeck** [comment]
Strangely, `apptools` on conda-forge seems to be broken, while it's working on `pip` with the same version designation

```
$ conda create -n test -c conda-forge apptools python=3.6
Solving environment: done

## Package Plan ##

  environment location: /anaconda3/envs/test

  added / updated specs: 
    - apptools
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    wheel-0.31.1               |           py36_0          62 KB  conda-forge
    libpng-1.6.35              |       ha92aebf_0         321 KB  conda-forge
    icu-58.2                   |       hfc679d8_0        22.8 MB  conda-forge
    six-1.11.0                 |           py36_1          20 KB  conda-forge
    pip-9.0.3                  |           py36_0         1.7 MB  conda-forge
    pyqt-5.6.0                 |   py36h8210e8a_6         4.2 MB  conda-forge
    setuptools-40.0.0          |           py36_0         550 KB  conda-forge
    certifi-2018.4.16          |           py36_0         142 KB  conda-forge
    sip-4.18                   |           py36_1         245 KB  conda-forge
    traits-4.6.0               |   py36h470a237_2         409 KB  conda-forge
    apptools-4.4.0             |             py_1         200 KB  conda-forge
    qt-5.6.2                   |       h9e3eb04_4        65.4 MB  conda-forge
    pygments-2.2.0             |             py_1         622 KB  conda-forge
    jpeg-9c                    |       h470a237_0         246 KB  conda-forge
    python-3.6.5               |                1        13.9 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       110.8 MB

The following NEW packages will be INSTALLED:

    apptools:        4.4.0-py_1           conda-forge
    ca-certificates: 2018.4.16-0          conda-forge
    certifi:         2018.4.16-py36_0     conda-forge
    configobj:       5.0.6-py36_0                    
    icu:             58.2-hfc679d8_0      conda-forge
    jpeg:            9c-h470a237_0        conda-forge
    libpng:          1.6.35-ha92aebf_0    conda-forge
    ncurses:         5.9-10               conda-forge
    openssl:         1.0.2o-0             conda-forge
    pip:             9.0.3-py36_0         conda-forge
    pyface:          6.0.0-py_1           conda-forge
    pygments:        2.2.0-py_1           conda-forge
    pyqt:            5.6.0-py36h8210e8a_6 conda-forge
    python:          3.6.5-1              conda-forge
    qt:              5.6.2-h9e3eb04_4     conda-forge
    readline:        7.0-0                conda-forge
    setuptools:      40.0.0-py36_0        conda-forge
    sip:             4.18-py36_1          conda-forge
    six:             1.11.0-py36_1        conda-forge
    sqlite:          3.20.1-2             conda-forge
    tk:              8.6.7-0              conda-forge
    traits:          4.6.0-py36h470a237_2 conda-forge
    traitsui:        6.0.0-py_1           conda-forge
    wheel:           0.31.1-py36_0        conda-forge
    xz:              5.2.3-0              conda-forge
    zlib:            1.2.11-h470a237_3    conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
wheel-0.31.1         |   62 KB | ##################################################################### | 100% 
libpng-1.6.35        |  321 KB | ##################################################################### | 100% 
icu-58.2             | 22.8 MB | ##################################################################### | 100% 
six-1.11.0           |   20 KB | ##################################################################### | 100% 
pip-9.0.3            |  1.7 MB | ##################################################################### | 100% 
pyqt-5.6.0           |  4.2 MB | ##################################################################### | 100% 
setuptools-40.0.0    |  550 KB | ##################################################################### | 100% 
certifi-2018.4.16    |  142 KB | ##################################################################### | 100% 
sip-4.18             |  245 KB | ##################################################################### | 100% 
traits-4.6.0         |  409 KB | ##################################################################### | 100% 
apptools-4.4.0       |  200 KB | ##################################################################### | 100% 
qt-5.6.2             | 65.4 MB | ##################################################################### | 100% 
pygments-2.2.0       |  622 KB | ##################################################################### | 100% 
jpeg-9c              |  246 KB | ##################################################################### | 100% 
python-3.6.5         | 13.9 MB | ##################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

ISRWKAVW2269F ~$ conda activate test
(test) ISRWKAVW2269F ~$ python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import apptools.scripting.recorder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/test/lib/python3.6/site-packages/apptools/scripting/recorder.py", line 15, in <module>
    import __builtin__
ModuleNotFoundError: No module named '__builtin__'
```

**Comment by mwcraig** [comment]
I’m going to close/reopen to retrigger the CI builds; turns out there was a problem with the new vtk builds at first....

**Comment by christianbrodbeck** [comment]
I opened an issue for the apptools-feedstock: 
https://github.com/conda-forge/apptools-feedstock/issues/7

**Comment by grlee77** [comment]
I fixed the apptools feedstock in conda-forge/apptools-feedstock#8.  I restarted some of the builds here, but so far only CircleCI has made it through the queue.  Unfortunately there is another, different Qt-related failure now on the mayavi.mlab import.:

```
import: 'tvtk'
import: 'tvtk.array_ext'
import: 'mayavi'
import: 'mayavi.mlab'
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Available platform plugins are: minimal, offscreen, xcb.

Reinstalling the application may fix this problem.
/home/conda/feedstock_root/build_artifacts/mayavi_1532312979329/test_tmp/conda_test_runner.sh: line 3:  3004 Aborted                 (core dumped) "/home/conda/feedstock_root/build_artifacts/mayavi_1532312979329/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python" -s "/home/conda/feedstock_root/build_artifacts/mayavi_1532312979329/test_tmp/run_test.py"
Tests failed for mayavi-4.6.1-py27h18b3941_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for mayavi-4.6.1-py27h18b3941_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
removing: mayavi-4.6.1-py27h18b3941_0.tar.bz2
TESTS FAILED: mayavi-4.6.1-py27h18b3941_0.tar.bz2
Exited with code 1
```

**Comment by christianbrodbeck** [comment]
And it looks like windows is pulling an outdated build of vtk (https://ci.appveyor.com/project/conda-forge/mayavi-feedstock/build/1.0.69/job/1ntn2k2ylr58gmqd#L2262) is it possible in `meta.yaml` to pin to a specific build?

**Comment by mwcraig** [comment]
I think you can pin; try setting minimum version instead of a hard pinning. The issue is that tconda prioritizes matching conda "features" over build numbers. The `_200` windows build had `vc14` as a feature but later ones don't (and anaconda is moving away from features, so they shouldn't be added back in). 

Might be worth asking about the right way to fix this for now on gitter: https://gitter.im/conda-forge/conda-forge.github.io

**Comment by christianbrodbeck** [comment]
Tried again with the new release, the macOS build passes. The `mlab` import test and corresponding Windows issue should probably be treated as a separate issue, especially since it does not seem to be a problem for distribution?

**Comment by christianbrodbeck** [comment]
Ping... This should not break anything because it does not modify current builds, just adds a new one.

**Comment by mwcraig** [comment]
Thanks for the reminder, merging....

**Comment by christianbrodbeck** [comment]
Thanks @mwcraig!

**Pull request merged**
