### PR TITLE
TEST:   import mayavi.mlab

### PR DESCRIPTION
**Pull request by christianbrodbeck**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Closing as stale.

**Comment by smithsp** [comment]
@ocefpaf I see that you closed this and #30  as well.  If we still think these changes are important, should we open a new pull request, or is your closing of these indicating that the change is not accepted?

**Comment by grlee77** [comment]
@smithsp: I am happy to merge this change if you create a new PR based on current master. 

IIRC there was an issue with this import in the past, so it would be good to test it.

**Comment by ocefpaf** [comment]
> @ocefpaf I see that you closed this and #30 as well. If we still think these changes are important, should we open a new pull request, or is your closing of these indicating that the change is not accepted?

Sure. I can reopened or you can send a new one. It is not irrelevante, it was just too old and without a maintainer working on it.

**Pull request closed without merging**
