### PR TITLE
Pin VTK

### PR DESCRIPTION
**Pull request by christianbrodbeck**
Addresses https://github.com/conda-forge/mayavi-feedstock/issues/28

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

### CODE REVIEW

**Comment by christianbrodbeck** [comment]
Ping?

**Comment by grlee77** [comment]
Sorry about never merging this one. 

It looks like #32 should supercede this PR, as it pins to `8.1.*` currently?

**Comment by christianbrodbeck** [comment]
I haven't been needing to pin manually recently. But from what I could tell, the error previously was due to conda installing VTK 8.1.0, and was solved by forcing 8.1.1, so I think pinning minor revision would still be desirable?

**Comment by grlee77** [comment]
Yeah, but do you think it should be updated to `>=8.1.1` or if there are issues with 8.2, then `>=8.1.1<8.2`? The CI builds in #32 are currently pulling in `8.1.2` which is the newest 8.1.x version (and the only `8.1.*` version that was compiled using the new compilers).

**Comment by christianbrodbeck** [comment]
I don't know enough about the compile process, is there a reason to believe that the minor revision has to be pinned (like something compiled against a specific version) or is there just something wrong with 1.8.0?

**Comment by grlee77** [comment]
I am not sure either, but I think we can use the following page as guidance:
https://abi-laboratory.pro/index.php?view=timeline&l=vtk

It looks like 8.1.1 added 5 new symbols relative to 8.1.0, but 8.1.2 has no new symbols relative to 8.1.1. So probably we can create a build pinned to ">=8.1.1,<8.2" and a separate one pinned to "8.2.0"

**Comment by christianbrodbeck** [comment]
Sounds good, although do we want two builds? Might we just pin to the most recent one unless cases come up where a different pin is needed?

**Comment by grlee77** [comment]
I think the build from #32 should work and pull in 8.1.2 by default at this point (although it may technically still be possible to get a broken combination if a user specifically requests 8.1.0). I am not sure it is worth making another more tightly pinned 8.1.2 build. Let's just move on to making a new build pinned to 8.2.0 now that it is avialable (see #34)

**Pull request closed without merging**
